steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - build
      - -t
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_IMAGE_NAME:$COMMIT_SHA'
      - -f
      - Dockerfile
      - .

  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - push
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_IMAGE_NAME:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '$_SERVICE_NAME'
      - --image
      - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_IMAGE_NAME:$COMMIT_SHA'
      - --region
      - '$_DEPLOY_REGION'
      - --platform
      - managed
      - --quiet

images:
  - '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_IMAGE_NAME:$COMMIT_SHA'

substitutions:
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_PROJECT_ID: emireqwebapp
  _AR_REPOSITORY: cloud-run-source-deploy
  _IMAGE_NAME: emireq-startup-dashboard-core/emireq-startup
  _SERVICE_NAME: emireq-startup
  _DEPLOY_REGION: europe-west1

options:
  logging: CLOUD_LOGGING_ONLY
